name: Android CI

on:
  pull_request:
    branches:
      - main

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Ktlint
        uses: lucasnlm/ktlint-action@master

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build with Gradle
        run: |
          ./gradlew testFossDebugUnitTest --stacktrace


  fdroid:
    name: F-droid build
    runs-on: ubuntu-latest

    steps:
      - name: Clone PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build for F-Droid
        run: |
          ./gradlew assembleFossDebug
